#!/bin/sh
set -e

# Create per-service roles and databases entirely from environment variables
# (populated from .env via docker-compose), so there is no hardcoded name/password.

psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<-SQL
  CREATE USER ${USER_DB_USER} WITH PASSWORD '${USER_DB_PASSWORD}';
  CREATE USER ${AUTH_DB_USER}  WITH PASSWORD '${AUTH_DB_PASSWORD}';
  CREATE USER ${AUTHORIZATION_DB_USER} WITH PASSWORD '${AUTHORIZATION_DB_PASSWORD}';
  CREATE USER ${DEPARTMENT_DB_USER} WITH PASSWORD '${DEPARTMENT_DB_PASSWORD}';
  CREATE USER ${EMPLOYEE_DB_USER} WITH PASSWORD '${EMPLOYEE_DB_PASSWORD}';
  CREATE USER ${CUSTOMER_DB_USER} WITH PASSWORD '${CUSTOMER_DB_PASSWORD}';
  CREATE USER ${CATEGORY_DB_USER} WITH PASSWORD '${CATEGORY_DB_PASSWORD}';
  CREATE USER ${SUPPLIER_DB_USER} WITH PASSWORD '${SUPPLIER_DB_PASSWORD}';
  CREATE USER ${COSMETIC_DB_USER} WITH PASSWORD '${COSMETIC_DB_PASSWORD}';
  CREATE USER ${INVENTORY_DB_USER} WITH PASSWORD '${INVENTORY_DB_PASSWORD}';
  CREATE USER ${PURCHASE_DB_USER} WITH PASSWORD '${PURCHASE_DB_PASSWORD}';

SQL

# Create databases only if they do not already exist (idempotent).
psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<-SQL
  SELECT 'CREATE DATABASE "$USER_DB_NAME" OWNER "$USER_DB_USER"'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$USER_DB_NAME')\gexec
  SELECT 'CREATE DATABASE "$AUTH_DB_NAME" OWNER "$AUTH_DB_USER"'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$AUTH_DB_NAME')\gexec
  SELECT 'CREATE DATABASE "$AUTHORIZATION_DB_NAME" OWNER "$AUTHORIZATION_DB_USER"'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$AUTHORIZATION_DB_NAME')\gexec
  SELECT 'CREATE DATABASE "$DEPARTMENT_DB_NAME" OWNER "$DEPARTMENT_DB_USER"'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$DEPARTMENT_DB_NAME')\gexec
  SELECT 'CREATE DATABASE "$EMPLOYEE_DB_NAME" OWNER "$EMPLOYEE_DB_USER"'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$EMPLOYEE_DB_NAME')\gexec
  SELECT 'CREATE DATABASE "$CUSTOMER_DB_NAME" OWNER "$CUSTOMER_DB_USER"'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$CUSTOMER_DB_NAME')\gexec
  SELECT 'CREATE DATABASE "$CATEGORY_DB_NAME" OWNER "$CATEGORY_DB_USER"'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$CATEGORY_DB_NAME')\gexec
  SELECT 'CREATE DATABASE "$SUPPLIER_DB_NAME" OWNER "$SUPPLIER_DB_USER"'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$SUPPLIER_DB_NAME')\gexec
  SELECT 'CREATE DATABASE "$COSMETIC_DB_NAME" OWNER "$COSMETIC_DB_USER"'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$COSMETIC_DB_NAME')\gexec
  SELECT 'CREATE DATABASE "$INVENTORY_DB_NAME" OWNER "$INVENTORY_DB_USER"'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$INVENTORY_DB_NAME')\gexec
  SELECT 'CREATE DATABASE "$PURCHASE_DB_NAME" OWNER "$PURCHASE_DB_USER"'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$PURCHASE_DB_NAME')\gexec
SQL

# Grant database privileges to each owner.
for pair in \
  "$USER_DB_NAME:$USER_DB_USER" \
  "$AUTH_DB_NAME:$AUTH_DB_USER" \
  "$AUTHORIZATION_DB_NAME:$AUTHORIZATION_DB_USER" \
  "$DEPARTMENT_DB_NAME:$DEPARTMENT_DB_USER" \
  "$EMPLOYEE_DB_NAME:$EMPLOYEE_DB_USER" \
  "$CUSTOMER_DB_NAME:$CUSTOMER_DB_USER" \
  "$CATEGORY_DB_NAME:$CATEGORY_DB_USER" \
  "$SUPPLIER_DB_NAME:$SUPPLIER_DB_USER" \
  "$COSMETIC_DB_NAME:$COSMETIC_DB_USER" \
  "$INVENTORY_DB_NAME:$INVENTORY_DB_USER" \
  "$PURCHASE_DB_NAME:$PURCHASE_DB_USER"; do
  db="${pair%%:*}"
  owner="${pair##*:}"
  psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" \
    -c "GRANT ALL PRIVILEGES ON DATABASE \"$db\" TO \"$owner\";"
done

# Grant schema-level privileges inside each created database.
grant_schema_privileges() {
  db="$1"
  owner="$2"
  psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$db" <<-SQL
    GRANT ALL PRIVILEGES ON SCHEMA public TO "$owner";
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "$owner";
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "$owner";
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "$owner";
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO "$owner";
SQL
}

grant_schema_privileges "$USER_DB_NAME" "$USER_DB_USER"
grant_schema_privileges "$AUTH_DB_NAME" "$AUTH_DB_USER"
grant_schema_privileges "$AUTHORIZATION_DB_NAME" "$AUTHORIZATION_DB_USER"
grant_schema_privileges "$DEPARTMENT_DB_NAME" "$DEPARTMENT_DB_USER"
grant_schema_privileges "$EMPLOYEE_DB_NAME" "$EMPLOYEE_DB_USER"
grant_schema_privileges "$CUSTOMER_DB_NAME" "$CUSTOMER_DB_USER"
grant_schema_privileges "$CATEGORY_DB_NAME" "$CATEGORY_DB_USER"
grant_schema_privileges "$SUPPLIER_DB_NAME" "$SUPPLIER_DB_USER"
grant_schema_privileges "$COSMETIC_DB_NAME" "$COSMETIC_DB_USER"
grant_schema_privileges "$INVENTORY_DB_NAME" "$INVENTORY_DB_USER"
grant_schema_privileges "$PURCHASE_DB_NAME" "$PURCHASE_DB_USER"
