export const GATEWAY_SERVICE_PORT = 3000;
export const USER_SERVICE_PORT = 3001;
export const AUTHENTICATION_SERVICE_PORT = 3002;
export const AUTHORIZATION_SERVICE_PORT = 3003;
export const DEPARTMENT_SERVICE_PORT = 3004;
