export enum Resource {
  Users = 'users',
  AuthUsers = 'auth_users',
  Customers = 'customers',
  Employees = 'employees',
  Departments = 'departments',
  Categories = 'categories',
  Suppliers = 'suppliers',
  Cosmetics = 'cosmetics',
  CosmeticVariants = 'cosmetic_variants',
  Inventory = 'inventory',
  Orders = 'orders',
  Invoices = 'invoices',
  Receipts = 'receipts',
  Payments = 'payments',
  PurchaseOrders = 'purchase_orders',
  StockAdjustments = 'stock_adjustments',
  Roles = 'roles',
  Permissions = 'permissions',
}